# Generated by Django 4.1.1 on 2022-10-23 21:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='sex',
            field=models.CharField(choices=[('mr', 'MR'), ('ms', 'MS')], default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
    ]
