# Generated by Django 4.1.1 on 2022-10-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0002_freelancer_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='sex',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Ms', 'Ms')], max_length=64),
        ),
    ]
