# Generated by Django 4.1.1 on 2022-10-24 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0003_alter_freelancer_sex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freelancer',
            old_name='sex',
            new_name='gender',
        ),
    ]
