# Generated by Django 4.1.1 on 2022-10-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0004_rename_sex_freelancer_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
