# Generated by Django 4.1.1 on 2022-10-24 15:46

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0005_freelancer_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Mr', 'Mr'), ('Ms', 'Ms')], max_length=64)),
                ('firstname', models.CharField(max_length=128, null=True)),
                ('lastname', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, help_text='+989125558877', max_length=64, null=True, unique=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('positions', models.ManyToManyField(help_text='What kind of Position this Freelancer has?', to='human_resources.position')),
                ('skills', models.ManyToManyField(help_text='What kind of skills this Freelancer has?', to='human_resources.skill')),
            ],
        ),
    ]
