# Generated by Django 4.1.1 on 2022-10-24 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0006_hire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hire',
            old_name='description',
            new_name='notes',
        ),
    ]
