# Generated by Django 4.1.1 on 2022-10-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0007_rename_description_hire_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hire',
            name='link',
        ),
        migrations.AddField(
            model_name='hire',
            name='interview_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
