# Generated by Django 4.1.1 on 2022-10-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0008_remove_hire_link_hire_interview_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hire',
            name='interviewed',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hire',
            name='potential',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
