# Generated by Django 4.1.1 on 2022-10-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0009_hire_interviewed_hire_potential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hire',
            name='interviewed',
            field=models.BooleanField(verbose_name='is Interviewed?'),
        ),
        migrations.AlterField(
            model_name='hire',
            name='phone',
            field=models.CharField(default=1, help_text='+989125558877', max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hire',
            name='potential',
            field=models.BooleanField(verbose_name='is Potential?'),
        ),
    ]
