# Generated by Django 4.1.1 on 2022-10-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0023_remove_project_freelancers_and_more'),
        ('human_resources', '0011_employee_remove_freelancer_positions_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Freelancer',
        ),
        migrations.AddField(
            model_name='employee',
            name='positions',
            field=models.ManyToManyField(help_text='What kind of Position this Employee has?', to='human_resources.position'),
        ),
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.ManyToManyField(help_text='What kind of skills this Employee has?', to='human_resources.skill'),
        ),
    ]
