# Generated by Django 4.1.1 on 2022-10-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0013_alter_employee_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='link',
        ),
        migrations.RemoveField(
            model_name='hire',
            name='email',
        ),
        migrations.AddField(
            model_name='hire',
            name='max_salary',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maximum Salary (Toman) '),
        ),
        migrations.AddField(
            model_name='hire',
            name='min_salary',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minimum Salary (Toman) '),
        ),
    ]
