# Generated by Django 4.1.1 on 2022-10-24 17:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0015_employee_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
