# Generated by Django 4.1.1 on 2022-10-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0018_employee_address_employee_city_employee_province_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='city',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='employee',
            name='province',
            field=models.CharField(max_length=64),
        ),
    ]
