# Generated by Django 4.1.1 on 2022-10-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0019_alter_employee_city_alter_employee_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='city',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='province',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
