# Generated by Django 4.1.1 on 2022-10-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0020_alter_employee_city_alter_employee_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(help_text='With dial code: +989125558877', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='positions',
            field=models.ManyToManyField(to='human_resources.position'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='skills',
            field=models.ManyToManyField(to='human_resources.skill'),
        ),
        migrations.AlterField(
            model_name='hire',
            name='max_salary',
            field=models.IntegerField(blank=True, help_text='per hour', null=True, verbose_name='Maximum Salary (Toman)'),
        ),
        migrations.AlterField(
            model_name='hire',
            name='min_salary',
            field=models.IntegerField(blank=True, help_text='per hour', null=True, verbose_name='Minimum Salary (Toman)'),
        ),
    ]
