# Generated by Django 4.1.1 on 2022-10-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0021_alter_employee_phone_alter_employee_positions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='plate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
