# Generated by Django 4.1.1 on 2022-10-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0023_hire_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hire',
            name='max_salary',
            field=models.IntegerField(blank=True, help_text='Hezar Tomnan per hour', null=True, verbose_name='Maximum Salary'),
        ),
        migrations.AlterField(
            model_name='hire',
            name='min_salary',
            field=models.IntegerField(blank=True, help_text='Hezar Tomnan per hour', null=True, verbose_name='Minimum Salary'),
        ),
        migrations.AlterField(
            model_name='hire',
            name='positions',
            field=models.ManyToManyField(to='human_resources.position'),
        ),
        migrations.AlterField(
            model_name='hire',
            name='skills',
            field=models.ManyToManyField(to='human_resources.skill'),
        ),
    ]
