# Generated by Django 4.1.1 on 2022-10-27 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0025_employee_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='hire',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('USDT', 'Tether'), ('IRR', 'Rial')], default=('USD', 'US Dollar'), max_length=128),
        ),
        migrations.AlterField(
            model_name='hire',
            name='max_salary',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maximum Salary'),
        ),
        migrations.AlterField(
            model_name='hire',
            name='min_salary',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minimum Salary'),
        ),
        migrations.AlterField(
            model_name='hire',
            name='positions',
            field=models.ManyToManyField(to='human_resources.position', verbose_name='Potential Positions'),
        ),
    ]
