# Generated by Django 4.1.1 on 2022-10-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0026_hire_currency_alter_hire_max_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hire',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('USDT', 'Tether'), ('IRR', 'Rial')], max_length=128),
        ),
    ]
