# Generated by Django 4.1.1 on 2022-10-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0027_alter_hire_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hire',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'US Dollar'), ('USDT', 'Tether'), ('IRR', 'Rial')], max_length=128, null=True),
        ),
    ]
