# Generated by Django 4.1.1 on 2022-10-29 00:23

from django.db import migrations, models
import human_resources.models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0029_alter_hire_max_salary_alter_hire_min_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='hire',
            name='attach',
            field=models.FileField(blank=True, null=True, upload_to=human_resources.models.upload_file_path),
        ),
    ]
