# Generated by Django 4.1.1 on 2022-10-29 02:05

from django.db import migrations, models
import human_resources.models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0030_hire_attach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hire',
            name='attach',
            field=models.FileField(blank=True, help_text='Like resume and CV', null=True, upload_to=human_resources.models.upload_file_path),
        ),
    ]
