# Generated by Django 4.1.1 on 2022-10-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0031_alter_hire_attach'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='telephone',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
