# Generated by Django 4.1.3 on 2022-11-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0033_alter_hire_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hire',
            name='interview_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
