# Generated by Django 4.1.3 on 2022-11-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0034_alter_hire_interview_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, help_text='This person is currently working'),
        ),
    ]
