# Generated by Django 4.1.1 on 2022-12-11 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0035_employee_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hire',
            name='currency',
        ),
    ]
