# Generated by Django 4.1.1 on 2022-12-11 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_income_currency'),
        ('human_resources', '0036_remove_hire_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='hire',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hire_currency', to='financial.currency'),
        ),
    ]
