# Generated by Django 4.1.1 on 2023-01-02 20:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0040_hire_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hire',
            name='rate',
            field=models.IntegerField(blank=True, help_text='1 is the worst, 10 is the best', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)]),
        ),
    ]
