# Generated by Django 4.1.1 on 2022-10-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_company_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
