# Generated by Django 4.1.1 on 2022-10-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_contact_link_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='gender',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Ms', 'Ms')], default=1, max_length=16),
            preserve_default=False,
        ),
    ]
