# Generated by Django 4.1.1 on 2022-10-24 17:13

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_contact_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='comment',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
    ]
