# Generated by Django 4.1.1 on 2022-10-24 17:14

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_contact_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='comment',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
