# Generated by Django 4.1.1 on 2022-10-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_company_address_company_city_company_province_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='firstname',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='lastname',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
