# Generated by Django 4.1.1 on 2022-10-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_alter_company_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contact',
            field=models.ManyToManyField(blank=True, to='contacts.contact'),
        ),
    ]
