# Generated by Django 4.1.1 on 2022-10-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0015_company_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='plate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
