# Generated by Django 4.1.1 on 2022-11-01 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0019_company_tags_contact_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='tags',
            field=models.ManyToManyField(blank=True, to='contacts.tag'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='tags',
            field=models.ManyToManyField(blank=True, to='contacts.tag'),
        ),
    ]
