# Generated by Django 4.1.3 on 2022-11-15 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0020_alter_company_tags_alter_contact_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(help_text='Client or Supplier', max_length=128, unique=True),
        ),
    ]
