# Generated by Django 4.1.1 on 2023-02-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0021_alter_tag_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='position',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
