# Generated by Django 4.1.1 on 2023-02-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0024_contact_facebook_contact_instagram_contact_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='middlename',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
