# Generated by Django 4.1.1 on 2023-02-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0025_contact_middlename'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='nickname',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
