# Generated by Django 4.1.1 on 2022-10-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_project_created_project_description_project_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Git or Django', max_length=128)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
