# Generated by Django 4.1.1 on 2022-10-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(to='management.skill'),
        ),
    ]
