# Generated by Django 4.1.1 on 2022-10-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_project_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(help_text='What kind of skills this project need?', to='management.skill'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='title',
            field=models.CharField(help_text='Git or Django', max_length=128, unique=True),
        ),
    ]
