# Generated by Django 4.1.1 on 2022-10-22 22:27

from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_freelancer'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freelancer',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='skills',
            field=models.ManyToManyField(help_text='What kind of skills this project need?', to='management.skill'),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
