# Generated by Django 4.1.1 on 2022-10-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_freelancer_email_freelancer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='phone',
            field=models.CharField(blank=True, help_text='+989125558877', max_length=64, null=True, unique=True),
        ),
    ]
