# Generated by Django 4.1.1 on 2022-10-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_freelancer_link_alter_freelancer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='firstname',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
