# Generated by Django 4.1.1 on 2022-10-22 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_position_alter_freelancer_skills_freelancer_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freelancer',
            old_name='position',
            new_name='positions',
        ),
    ]
