# Generated by Django 4.1.1 on 2022-10-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_rename_position_freelancer_positions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='firstname',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
