# Generated by Django 4.1.1 on 2022-10-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_alter_freelancer_firstname'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='freelancers',
            field=models.ManyToManyField(help_text='which people work on this project?', to='management.freelancer'),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='positions',
            field=models.ManyToManyField(help_text='What kind of Position this Freelancer has?', to='management.position'),
        ),
    ]
