# Generated by Django 4.1.1 on 2022-10-22 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_project_freelancers_alter_freelancer_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('start', 'Start'), ('finished', 'Finished')], default=('start', 'Start'), max_length=128),
        ),
    ]
