# Generated by Django 4.1.1 on 2022-10-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0001_initial'),
        ('management', '0017_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='freelancers',
            field=models.ManyToManyField(help_text='which people work on this project?', to='human_resources.freelancer'),
        ),
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(help_text='What kind of skills this project need?', to='human_resources.skill'),
        ),
        migrations.DeleteModel(
            name='Freelancer',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
