# Generated by Django 4.1.1 on 2022-10-23 20:31

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_timesheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
