# Generated by Django 4.1.1 on 2022-10-23 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_timesheet_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='time',
        ),
    ]
