# Generated by Django 4.1.1 on 2022-10-24 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0011_employee_remove_freelancer_positions_and_more'),
        ('management', '0022_remove_timesheet_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='freelancers',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='freelancer',
        ),
        migrations.AddField(
            model_name='project',
            name='employees',
            field=models.ManyToManyField(help_text='which people work on this project?', to='human_resources.employee'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='human_resources.employee'),
            preserve_default=False,
        ),
    ]
