# Generated by Django 4.1.1 on 2022-10-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0023_remove_project_freelancers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='hour_work',
            field=models.IntegerField(default=1, help_text='Hour work - like 7.5 -> 07:50'),
            preserve_default=False,
        ),
    ]
