# Generated by Django 4.1.1 on 2022-10-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0024_timesheet_hour_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='hour_work',
            field=models.CharField(help_text='Hour work - like 07:50 -> 7.5', max_length=4),
        ),
    ]
