# Generated by Django 4.1.1 on 2022-10-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0025_alter_timesheet_hour_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='term',
            field=models.CharField(choices=[('short', 'Short-term or part-time work (Less than 30hr/week and less than 3 months)'), ('long', 'Long-term / More than 30 hrs/week and more than 3 months')], default=('short', 'Short-term or part-time work (Less than 30hr/week and less than 3 months)'), max_length=256),
        ),
    ]
