# Generated by Django 4.1.1 on 2022-10-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0027_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='people',
            field=models.IntegerField(default=1, help_text='How many people this project need?'),
        ),
        migrations.AlterField(
            model_name='project',
            name='term',
            field=models.CharField(choices=[('short', 'Short-term or part-time work: Less than 30hr/week and less than 3 months'), ('long', 'Long-term work: More than 30 hrs/week and more than 3 months')], default=('short', 'Short-term or part-time work: Less than 30hr/week and less than 3 months'), max_length=256),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[(0, 'One-time project'), (1, 'Ongoing project'), (2, 'Complex project')], default=('short', 'Short-term or part-time work: Less than 30hr/week and less than 3 months'), max_length=256),
        ),
    ]
