# Generated by Django 4.1.1 on 2022-10-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0028_project_people_alter_project_term_alter_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='budget_type',
            field=models.CharField(choices=[(0, 'Pay by the hour'), (1, 'Pay a fixed price')], default=(0, 'Pay by the hour'), max_length=256),
        ),
    ]
