# Generated by Django 4.1.1 on 2022-10-25 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0029_project_budget_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='type',
            new_name='project_type',
        ),
    ]
