# Generated by Django 4.1.1 on 2022-10-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0030_rename_type_project_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='fixed_budget',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='max_budget',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='min_budget',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
