# Generated by Django 4.1.1 on 2022-10-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0031_project_fixed_budget_project_max_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='budget_type',
            field=models.CharField(choices=[('hour', 'Pay by the hour'), ('fixed', 'Pay a fixed price')], default=('hour', 'Pay by the hour'), max_length=256),
        ),
        migrations.AlterField(
            model_name='project',
            name='max_budget',
            field=models.IntegerField(blank=True, default=0, help_text='Maximum price per hour work', null=True, verbose_name='max pay / hour'),
        ),
        migrations.AlterField(
            model_name='project',
            name='min_budget',
            field=models.IntegerField(blank=True, default=0, help_text='Minimum price per hour work', null=True, verbose_name='Min pay / hour'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('onetime', 'One-time project'), ('ongoing', 'Ongoing project'), ('complex', 'Complex project')], default=('short', 'Short-term or part-time work: Less than 30hr/week and less than 3 months'), max_length=256),
        ),
    ]
