# Generated by Django 4.1.1 on 2022-10-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0032_alter_project_budget_type_alter_project_max_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='fixed_budget',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
