# Generated by Django 4.1.1 on 2022-10-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0036_timesheet_currency_timesheet_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='experience_level',
            field=models.CharField(choices=[('expert', 'Expert'), ('intermediate', 'Intermediate')], default=('expert', 'Expert'), max_length=256),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='price',
            field=models.BigIntegerField(help_text='hourly price for working on this project'),
        ),
    ]
