# Generated by Django 4.1.1 on 2022-10-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0037_project_experience_level_alter_timesheet_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='duration',
            field=models.CharField(choices=[(0, 'Less than 1 month'), (1, 'More than 1 month'), (2, '1 to 3 months'), (3, '3 to 6 months'), (4, 'More than 6 months')], default=(0, 'Less than 1 month'), max_length=256),
        ),
        migrations.AlterField(
            model_name='project',
            name='experience_level',
            field=models.CharField(choices=[('expert', 'Expert'), ('intermediate', 'Intermediate'), ('beginner', 'Beginner')], default=('expert', 'Expert'), max_length=256),
        ),
    ]
