# Generated by Django 4.1.1 on 2022-10-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0039_alter_project_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='currency',
            field=models.CharField(choices=[('IRR', 'Rial'), ('USD', 'US Dollar'), ('USDT', 'Tether')], default=('IRR', 'Rial'), max_length=256),
        ),
    ]
