# Generated by Django 4.1.1 on 2022-10-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0040_project_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('USDT', 'Tether'), ('IRR', 'Rial')], default=('USD', 'US Dollar'), max_length=256),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('USDT', 'Tether'), ('IRR', 'Rial')], default=('USD', 'US Dollar'), max_length=64),
        ),
    ]
