# Generated by Django 4.1.1 on 2022-10-28 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0016_company_plate'),
        ('management', '0041_alter_project_currency_alter_timesheet_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_company', to='contacts.company'),
        ),
        migrations.AddField(
            model_name='project',
            name='contact',
            field=models.ManyToManyField(blank=True, related_name='project_contact', to='contacts.company', verbose_name='Contact(s)'),
        ),
    ]
