# Generated by Django 4.1.1 on 2022-10-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0016_company_plate'),
        ('management', '0042_project_company_project_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contact',
            field=models.ManyToManyField(blank=True, help_text='Who are we in touch with in this project?', related_name='project_contact', to='contacts.contact', verbose_name='Contact(s)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(help_text='Project name or title', max_length=512, verbose_name='Name'),
        ),
    ]
