# Generated by Django 4.1.1 on 2022-10-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0043_alter_project_contact_alter_project_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('not-started', 'Not started'), ('active', 'Active'), ('overdue', 'Overdue'), ('pending', 'Pending'), ('canceled', 'Canceled'), ('priority', 'Priority'), ('completed', 'Completed')], default=('upcoming', 'Upcoming'), help_text='https://www.indeed.com/career-advice/career-development/project-statuses', max_length=128),
        ),
    ]
