# Generated by Django 4.1.1 on 2022-10-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0044_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
