# Generated by Django 4.1.1 on 2022-10-30 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0032_employee_telephone'),
        ('management', '0046_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('programming', 'Programming'), ('wordpress', 'Wordpress'), ('seo', 'SEO')], default=('programming', 'Programming'), max_length=256),
        ),
        migrations.AlterField(
            model_name='project',
            name='employees',
            field=models.ManyToManyField(blank=True, help_text='which people work on this project?', to='human_resources.employee', verbose_name='Employee(s)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('onetime', 'One-time project'), ('ongoing', 'Ongoing project'), ('complex', 'Complex project')], default=('onetime', 'One-time project'), max_length=256),
        ),
    ]
