# Generated by Django 4.1.1 on 2022-11-03 23:46

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0047_alter_project_category_alter_project_employees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(blank=True, choices_display='WITH_GMT_OFFSET', null=True),
        ),
    ]
