# Generated by Django 4.1.1 on 2022-11-07 00:51

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0048_project_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(blank=True, choices_display='WITH_GMT_OFFSET', help_text='Client Timezone', null=True),
        ),
    ]
