# Generated by Django 4.1.1 on 2022-11-07 01:11

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0049_alter_project_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('programming', 'Programming'), ('wordpress', 'Wordpress'), ('seo', 'SEO')], default=('programming', 'Programming'), max_length=256),
        ),
    ]
