# Generated by Django 4.1.3 on 2022-11-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0052_project_country_alter_project_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='payment_type',
            field=models.CharField(choices=[('hour', 'Pay by the hour'), ('fixed', 'Pay a fixed price')], default=('hour', 'Pay by the hour'), max_length=256),
        ),
    ]
