# Generated by Django 4.1.3 on 2022-11-15 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0054_remove_timesheet_price_timesheet_payment_fixed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='payment_fixed',
            field=models.BigIntegerField(blank=True, help_text='payment is not by hour', null=True),
        ),
    ]
