# Generated by Django 4.1.1 on 2022-12-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0058_project_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='fixed_budget',
        ),
        migrations.RemoveField(
            model_name='project',
            name='max_budget',
        ),
        migrations.RemoveField(
            model_name='project',
            name='min_budget',
        ),
        migrations.AddField(
            model_name='project',
            name='budget',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='estimation',
            field=models.BooleanField(default=False, help_text='is the?'),
        ),
    ]
