# Generated by Django 4.1.1 on 2022-12-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0059_remove_project_fixed_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='estimation',
            field=models.BooleanField(default=False, help_text='Is this budget an estimation?'),
        ),
    ]
