# Generated by Django 4.1.1 on 2022-12-11 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0060_alter_project_budget_alter_project_estimation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='experience_level',
        ),
    ]
