# Generated by Django 4.1.1 on 2022-12-11 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0061_remove_project_experience_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_type',
        ),
    ]
