# Generated by Django 4.1.1 on 2022-12-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0063_remove_project_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='SEO or WordPress', max_length=128, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ManyToManyField(to='management.category', verbose_name='Category(s)'),
        ),
    ]
