# Generated by Django 4.1.1 on 2022-12-11 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0065_alter_category_options_remove_project_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Categories',
            new_name='Category',
        ),
    ]
