# Generated by Django 4.1.1 on 2022-12-12 07:09

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0066_rename_categories_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=tinymce.models.HTMLField(blank=True, help_text='you can write project agreement, duties or salary of each person or any other thing', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='source',
            field=models.CharField(choices=[('upwork', 'UpWork'), ('freelancer', 'Freelancer'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('website', 'Website'), ('direct', 'Direct')], default=('upwork', 'UpWork'), max_length=32),
        ),
    ]
