# Generated by Django 4.1.1 on 2022-12-12 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0067_alter_project_description_alter_project_source'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeSheet',
        ),
    ]
