# Generated by Django 4.1.1 on 2023-02-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0069_alter_project_budget_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='people',
            field=models.IntegerField(blank=True, default=1, help_text='How many people this project need?', null=True),
        ),
    ]
