# Generated by Django 4.1.1 on 2023-05-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0071_remove_project_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('not-started', 'Not started'), ('active', 'Active'), ('overdue', 'Overdue'), ('pending', 'Pending'), ('canceled', 'Canceled'), ('priority', 'Priority'), ('completed', 'Completed'), ('refunded', 'Refunded'), ('failed', 'Failed')], default=('upcoming', 'Upcoming'), help_text='https://www.indeed.com/career-advice/career-development/project-statuses', max_length=128),
        ),
    ]
