# Generated by Django 4.1.1 on 2022-12-11 10:37

from django.db import migrations, models
import django.db.models.deletion
import financial.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0066_rename_categories_project_category'),
        ('human_resources', '0035_employee_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Resalat or Meli', max_length=128, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(help_text='16 Digits card number without dash', max_length=20)),
                ('account_number', models.CharField(help_text='Shomare Hesab', max_length=40)),
                ('sheba', models.CharField(max_length=80)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(help_text='Bank name', null=True, on_delete=django.db.models.deletion.CASCADE, to='financial.bank')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_resources.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Rial or US Dollar', max_length=128, unique=True)),
                ('code', models.SlugField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advance_payment', models.BooleanField(default=False, help_text='Prepayment or advance payment to the freelancer')),
                ('price', models.BigIntegerField(null=True)),
                ('date', models.DateField(null=True, verbose_name='Pay Date')),
                ('attach', models.FileField(blank=True, null=True, upload_to=financial.models.upload_file_path)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financial.bankaccount')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.currency')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='human_resources.employee')),
                ('project', models.ManyToManyField(blank=True, related_name='salary_project', to='management.project', verbose_name='Project(s)')),
            ],
            options={
                'verbose_name_plural': 'Salaries',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='2nd payment from Django project X', max_length=512, null=True)),
                ('price', models.BigIntegerField(null=True)),
                ('date', models.DateField(null=True, verbose_name='Income Date')),
                ('link', models.URLField(blank=True, null=True)),
                ('attach', models.FileField(blank=True, null=True, upload_to=financial.models.upload_file_path)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='income_project', to='management.project')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Buy VPS', max_length=512, null=True)),
                ('to', models.CharField(help_text='UpWork, Uber ETC', max_length=256, null=True)),
                ('price', models.BigIntegerField(help_text='Be careful with zeros!', null=True)),
                ('source', models.CharField(choices=[('employee', 'Employee'), ('company', 'Company')], default=('employee', 'Employee'), help_text='Who payed this expense?', max_length=32)),
                ('date', models.DateField(null=True, verbose_name='Pay Date')),
                ('link', models.URLField(blank=True, null=True)),
                ('attach', models.FileField(blank=True, null=True, upload_to=financial.models.upload_file_path)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.currency')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_resources.employee')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_project', to='management.project')),
            ],
        ),
    ]
