# Generated by Django 4.1.1 on 2022-10-26 12:34

from django.db import migrations, models
import django.db.models.deletion
import financial.models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0039_alter_project_duration'),
        ('human_resources', '0025_employee_country'),
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salary',
            options={'verbose_name_plural': 'Salaries'},
        ),
        migrations.AddField(
            model_name='expense',
            name='attach',
            field=models.FileField(blank=True, null=True, upload_to=financial.models.upload_file_path),
        ),
        migrations.AddField(
            model_name='expense',
            name='comment',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('IRR', 'Rial'), ('USD', 'US Dollar'), ('USDT', 'Tether')], default=('IRR', 'Rial'), max_length=64),
        ),
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateField(null=True, verbose_name='Pay Date'),
        ),
        migrations.AddField(
            model_name='expense',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='price',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.project'),
        ),
        migrations.AddField(
            model_name='expense',
            name='title',
            field=models.CharField(help_text='Buy VPS', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='to',
            field=models.CharField(help_text='UpWork, Uber ETC', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='attach',
            field=models.FileField(blank=True, null=True, upload_to=financial.models.upload_file_path),
        ),
        migrations.AddField(
            model_name='income',
            name='comment',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='currency',
            field=models.CharField(choices=[('IRR', 'Rial'), ('USD', 'US Dollar'), ('USDT', 'Tether')], default=('USD', 'US Dollar'), max_length=64),
        ),
        migrations.AddField(
            model_name='income',
            name='date',
            field=models.DateField(null=True, verbose_name='Income Date'),
        ),
        migrations.AddField(
            model_name='income',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='price',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.project'),
        ),
        migrations.AddField(
            model_name='income',
            name='title',
            field=models.CharField(help_text='2nd payment from Django project X', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='salary',
            name='attach',
            field=models.FileField(blank=True, null=True, upload_to=financial.models.upload_file_path),
        ),
        migrations.AddField(
            model_name='salary',
            name='comment',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salary',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='salary',
            name='currency',
            field=models.CharField(choices=[('IRR', 'Rial'), ('USD', 'US Dollar'), ('USDT', 'Tether')], default=('IRR', 'Rial'), max_length=64),
        ),
        migrations.AddField(
            model_name='salary',
            name='date',
            field=models.DateField(null=True, verbose_name='Pay Date'),
        ),
        migrations.AddField(
            model_name='salary',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='human_resources.employee'),
        ),
        migrations.AddField(
            model_name='salary',
            name='price',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='salary',
            name='title',
            field=models.CharField(help_text='2nd payment to mr X', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='salary',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
