# Generated by Django 4.1.1 on 2022-10-22 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_project_status'),
        ('financial', '0002_alter_salary_options_expense_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='management.project'),
            preserve_default=False,
        ),
    ]
