# Generated by Django 4.1.1 on 2022-10-27 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_alter_salary_options_expense_attach_expense_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
