# Generated by Django 4.1.1 on 2022-12-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_income_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(blank=True, help_text='Shomare Hesab', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='sheba',
            field=models.CharField(blank=True, help_text='Without IR', max_length=80, null=True),
        ),
    ]
