# Generated by Django 4.1.1 on 2022-10-27 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_alter_income_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
