# Generated by Django 4.1.1 on 2022-10-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_income_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='currency',
            field=models.CharField(choices=[('IRR', 'Rial'), ('USD', 'US Dollar')], default=('USD', 'US Dollar'), max_length=64),
        ),
    ]
