# Generated by Django 4.1.1 on 2022-12-13 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0004_paypal_income_paypal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paypal',
            name='currency',
        ),
    ]
