# Generated by Django 4.1.1 on 2022-10-27 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0004_alter_expense_comment_alter_salary_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='title',
        ),
    ]
