# Generated by Django 4.1.1 on 2022-10-24 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0012_delete_freelancer_employee_positions_employee_skills'),
        ('financial', '0004_alter_income_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='human_resources.employee'),
            preserve_default=False,
        ),
    ]
