# Generated by Django 4.1.1 on 2022-12-13 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0005_remove_paypal_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financial.bankaccount', verbose_name='Bank Account'),
        ),
        migrations.AlterField(
            model_name='income',
            name='paypal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financial.paypal', verbose_name='Paypal Account'),
        ),
    ]
