# Generated by Django 4.1.1 on 2022-10-24 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0025_alter_timesheet_hour_work'),
        ('financial', '0005_salary_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.project'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('IRR', 'Rial'), ('USD', 'US Dollar'), ('USDT', 'Tether')], default=('IRR', 'Rial'), max_length=64),
        ),
        migrations.AlterField(
            model_name='income',
            name='currency',
            field=models.CharField(choices=[('IRR', 'Rial'), ('USD', 'US Dollar'), ('USDT', 'Tether')], default=('USD', 'US Dollar'), max_length=64),
        ),
        migrations.AlterField(
            model_name='salary',
            name='currency',
            field=models.CharField(choices=[('IRR', 'Rial'), ('USD', 'US Dollar'), ('USDT', 'Tether')], default=('IRR', 'Rial'), max_length=64),
        ),
    ]
