# Generated by Django 4.1.1 on 2022-10-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0041_alter_project_currency_alter_timesheet_currency'),
        ('financial', '0006_salary_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='project',
            field=models.ManyToManyField(blank=True, to='management.project', verbose_name='Project(s)'),
        ),
    ]
