# Generated by Django 4.1.1 on 2022-10-24 19:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0006_expense_project_alter_expense_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='to',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
    ]
