# Generated by Django 4.1.1 on 2022-10-28 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0007_alter_salary_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='project',
        ),
        migrations.RemoveField(
            model_name='income',
            name='project',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='project',
        ),
    ]
