# Generated by Django 4.1.1 on 2022-12-13 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0007_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financial.wallet', verbose_name='Wallet Address'),
        ),
    ]
