# Generated by Django 4.1.1 on 2022-10-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0007_expense_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='description',
            new_name='comment',
        ),
        migrations.AlterField(
            model_name='expense',
            name='to',
            field=models.CharField(help_text='UpWork, Uber ETC', max_length=256),
        ),
    ]
