# Generated by Django 4.1.1 on 2022-12-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0008_income_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
