# Generated by Django 4.1.1 on 2022-10-24 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0008_rename_description_expense_comment_alter_expense_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='description',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='salary',
            old_name='description',
            new_name='comment',
        ),
    ]
