# Generated by Django 4.1.1 on 2022-10-28 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0041_alter_project_currency_alter_timesheet_currency'),
        ('financial', '0008_remove_expense_project_remove_income_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Project', to='management.project'),
        ),
    ]
