# Generated by Django 4.1.1 on 2022-10-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0009_rename_description_income_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='attach',
            field=models.FileField(default=1, upload_to='attach/'),
            preserve_default=False,
        ),
    ]
