# Generated by Django 4.1.1 on 2022-12-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0009_wallet_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='address',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='network',
            field=models.CharField(max_length=64),
        ),
    ]
