# Generated by Django 4.1.1 on 2022-10-28 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0041_alter_project_currency_alter_timesheet_currency'),
        ('financial', '0010_salary_project_alter_expense_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='income_project', to='management.project'),
        ),
    ]
