# Generated by Django 4.1.1 on 2022-10-30 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0032_employee_telephone'),
        ('financial', '0011_income_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='human_resources.employee'),
            preserve_default=False,
        ),
    ]
