# Generated by Django 4.1.1 on 2022-10-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0012_expense_payer'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='source',
            field=models.CharField(choices=[('employee', 'Employee'), ('company', 'Company')], default=('employee', 'Employee'), max_length=32),
        ),
    ]
