# Generated by Django 4.1.1 on 2022-10-30 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0013_expense_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('USDT', 'Tether'), ('IRR', 'Rial')], default=('IRR', 'Rial'), max_length=64),
        ),
        migrations.AlterField(
            model_name='expense',
            name='source',
            field=models.CharField(choices=[('employee', 'Employee'), ('company', 'Company')], default=('employee', 'Employee'), help_text='Who payed this expense?', max_length=32),
        ),
        migrations.AlterField(
            model_name='income',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('USDT', 'Tether'), ('IRR', 'Rial')], default=('USD', 'US Dollar'), max_length=64),
        ),
        migrations.AlterField(
            model_name='salary',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('USDT', 'Tether'), ('IRR', 'Rial')], default=('IRR', 'Rial'), max_length=64),
        ),
    ]
