# Generated by Django 4.1.1 on 2022-12-13 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0013_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
    ]
