# Generated by Django 4.1.1 on 2022-11-03 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0014_alter_expense_currency_alter_expense_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='price',
            field=models.BigIntegerField(help_text='Be careful with zeros!', null=True),
        ),
    ]
