# Generated by Django 4.1.1 on 2022-12-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0015_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='email',
            field=models.EmailField(blank=True, help_text='Mostly for paypal account', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='phone_number',
            field=models.CharField(blank=True, help_text='example: +989981105577', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='card_number',
            field=models.CharField(blank=True, help_text='16 Digits card number without dash', max_length=20, null=True),
        ),
    ]
