# Generated by Django 4.1.3 on 2022-11-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0015_alter_expense_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='advance_payment',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
