# Generated by Django 4.1.1 on 2022-12-14 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0016_bankaccount_email_bankaccount_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='paypal',
        ),
        migrations.DeleteModel(
            name='Paypal',
        ),
    ]
