# Generated by Django 4.1.1 on 2022-12-14 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0037_hire_currency'),
        ('financial', '0018_alter_salary_bank_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='human_resources.employee', verbose_name='To employee'),
        ),
    ]
