# Generated by Django 4.1.1 on 2023-02-15 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0019_alter_salary_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='title',
        ),
    ]
