# Generated by Django 4.1.3 on 2022-11-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0019_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(blank=True, help_text='Shomare Hesab', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='card_number',
            field=models.CharField(blank=True, help_text='16 Digits card number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='sheba',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
