# Generated by Django 4.1.3 on 2022-11-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0020_bankaccount_account_number_bankaccount_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(help_text='Shomare Hesab', max_length=40),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='card_number',
            field=models.CharField(help_text='16 Digits card number', max_length=20),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='sheba',
            field=models.CharField(max_length=80),
        ),
    ]
