# Generated by Django 4.1.1 on 2023-02-15 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0023_expense_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='to',
        ),
    ]
