# Generated by Django 4.1.3 on 2022-11-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0023_bankaccount_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='card_number',
            field=models.CharField(help_text='16 Digits card number without dash', max_length=20),
        ),
    ]
