# Generated by Django 4.1.1 on 2023-02-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0025_expense_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='title',
            field=models.CharField(help_text='2nd payment from Django project X', max_length=512, null=True),
        ),
    ]
