# Generated by Django 4.1.3 on 2022-11-26 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0025_salary_bank_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='bank',
            field=models.ForeignKey(help_text='Bank name', null=True, on_delete=django.db.models.deletion.CASCADE, to='financial.bank'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='bank_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='financial.bankaccount'),
            preserve_default=False,
        ),
    ]
