# Generated by Django 4.1.1 on 2023-02-16 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0026_income_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='title',
        ),
    ]
