# Generated by Django 4.1.3 on 2022-11-26 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0026_alter_bankaccount_bank_alter_salary_bank_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financial.bankaccount'),
        ),
    ]
