# Generated by Django 4.1.1 on 2023-02-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0029_remove_income_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='title',
            field=models.CharField(default='', help_text='2nd payment from Django project X', max_length=512),
            preserve_default=False,
        ),
    ]
