# Generated by Django 4.1.1 on 2023-02-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0030_income_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='title',
            field=models.CharField(blank=True, help_text='2nd payment from Django project X', max_length=512, null=True),
        ),
    ]
