# Generated by Django 4.1.1 on 2023-05-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0033_alter_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
