# Generated by Django 4.1.1 on 2023-05-20 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0026_contact_nickname'),
        ('financial', '0035_salary_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.company'),
        ),
    ]
