# Generated by Django 4.1.1 on 2023-05-20 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0043_alter_employee_birthday_alter_employee_email_and_more'),
        ('financial', '0036_salary_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='human_resources.employee'),
        ),
    ]
