# Generated by Django 3.2.10 on 2023-08-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0037_alter_salary_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='price',
            field=models.FloatField(default=0, help_text='Be careful with zeros!', null=True),
        ),
    ]
