# Generated by Django 4.1.1 on 2022-10-28 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arshidipedia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='test',
        ),
    ]
