# Generated by Django 4.1.1 on 2022-10-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arshidipedia', '0003_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
