# Generated by Django 4.1.1 on 2022-10-28 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arshidipedia', '0004_archive_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Archive',
        ),
    ]
