# Generated by Django 4.1.1 on 2022-10-28 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0029_alter_hire_max_salary_alter_hire_min_salary'),
        ('arshidipedia', '0005_delete_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='human_resources.employee'),
        ),
    ]
