# Generated by Django 4.1.1 on 2022-10-29 02:06

import arshidipedia.models
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('arshidipedia', '0006_file_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('file', models.FileField(upload_to=arshidipedia.models.upload_file_path)),
                ('content', tinymce.models.HTMLField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
