# Generated by Django 4.1.1 on 2022-10-29 02:13

import arshidipedia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arshidipedia', '0008_alter_pedia_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedia',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedia',
            name='file',
            field=models.FileField(blank=True, help_text='Upload your pdf, docx, .... file in here', null=True, upload_to=arshidipedia.models.upload_file_path),
        ),
    ]
