# Generated by Django 4.1.1 on 2022-10-29 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arshidipedia', '0009_pedia_link_alter_pedia_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pedia',
            new_name='Library',
        ),
    ]
