# Generated by Django 4.1.1 on 2022-10-29 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arshidipedia', '0010_rename_pedia_library'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='library',
            options={'verbose_name_plural': 'Library'},
        ),
        migrations.AddField(
            model_name='library',
            name='category',
            field=models.CharField(choices=[('web-development', 'Web Development'), ('seo', 'SEO'), ('wordpress', 'Wordpress')], default=('web-development', 'Web Development'), max_length=128),
        ),
    ]
