# Generated by Django 4.1.1 on 2022-10-30 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0032_employee_telephone'),
        ('arshidipedia', '0012_alter_library_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='employee',
            field=models.ForeignKey(blank=True, help_text='This file belongs to whom?', null=True, on_delete=django.db.models.deletion.CASCADE, to='human_resources.employee'),
        ),
    ]
