# Generated by Django 4.1.3 on 2022-11-15 23:07

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('arshidipedia', '0013_alter_file_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('web-development', 'Web Development'), ('seo', 'SEO'), ('wordpress', 'Wordpress')], default=('web-development', 'Web Development'), max_length=128),
        ),
    ]
