# Generated by Django 4.1.3 on 2022-11-15 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arshidipedia', '0015_category_remove_library_category_library_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
